services:
  mahalla_account:
    build: .
    container_name: mahalla_account_web
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/media_static
      - media_volume:/app/media
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
      - redis
      - go2rtc
    entrypoint: ["./wait-for-it.sh", "db:5432", "--"]
    command: >
      sh -lc "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 main.asgi:application
      "

  db:
    image: postgis/postgis:15-3.3
    container_name: mahalla_account_base
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mahalla_account_db
      POSTGRES_USER: mahalla_account_user
      POSTGRES_PASSWORD: mahalla_account_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mahalla_account_redis
    restart: always
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: mahalla_account_celery
    restart: always
    command: celery -A main worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    container_name: mahalla_account_celery_beat
    restart: always
    command: celery -A main beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  damafon-listener:
    build: .
    container_name: mahalla_account_damafon_listener
    restart: always
    command: python manage.py damafon_listener
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  go2rtc:
    image: alexxit/go2rtc
    container_name: mahalla_go2rtc
    restart: always
    ports:
      - "1984:1984"   # REST API + WebRTC WebSocket
      - "8554:8554"   # RTSP
      - "8555:8555/tcp"
      - "8555:8555/udp"
    volumes:
      - ./go2rtc.yaml:/config/go2rtc.yaml

  nginx:
    image: nginx:alpine
    container_name: mahalla_account_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/media_static
      - media_volume:/app/media
      - nginx_cache:/var/cache/nginx
    depends_on:
      - mahalla_account

volumes:
  postgres_data:
  static_volume:
  media_volume:
  nginx_cache:
